server:
  port: 8081
#  address:  10.40.245.251
  ssl:
    key-store: classpath:4071328_cky666.top.pfx
#    key-password: n5wB62w3
    #    key-alias:
    key-store-type: PKCS12
    key-store-password: n5wB62w3
  #    enabled-protocols: HTTP/1.1
#    enabled: true
#    scheme: https
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      encoding: UTF-8
  servlet:
    session:
      cookie:
        max-age: 1800
      timeout: 1800
spring:
  session:
    timeout: 1800
    store-type: redis
    redis:
      namespace: securtity_session
      flush-mode: on_save
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://47.101.179.127:3306/school_job?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: zq
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 60000
      connection-timeout: 1000
  redis:
    database: 0
    host: 47.101.179.127
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        min-idle: 0
#    timeout: 1000

# 日志配置
logging:
  level:
#    com.ruoyi: debug
    org.springframework: warn
# mybatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hooli.work.entity
  global-config:
    db-config:
      #主键类型：auto主键自增，input用户输入id，id_worker全局唯一数字id，UUID全局唯一的UUID
      id-type: auto
      #字段策略
      field-strategy: not_empty
      #开启驼峰是命名
      table-underline: true

# elasticsearch配置
#elasticsearch:
#  host: 101.37.31.188
#  port: 9200
#  schema: http
#  connectionRequestTimeOut: 10000
#  socketTimeOut: 30000
#  maxConnectNum: 100
#  maxConnectPerRoute: 100
#  uniqueConnectTimeConfig: false
#  uniqueConnectNumConfig: true
