server:
  port: 8081
#  address:  192.168.43.84
  ssl:
    key-store: src\main\resources\cky666-tomcat.jks
    key-password: 123456
    #    key-alias:
    key-store-type: JKS
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://rm-bp1np46rt3na0655zlo.mysql.rds.aliyuncs.com:3306/db_02?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: sb
    password: 1QAZ!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 60000
      connection-timeout: 1000

  redis:
    database: 0
    host: 101.37.31.188
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        min-idle: 0
    timeout: 1000


# mybatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hooli.work.entity
  global-config:
    db-config:
      #主键类型：auto主键自增，input用户输入id，id_worker全局唯一数字id，UUID全局唯一的UUID
      id-type: auto
      #字段策略
      field-strategy: not_empty
      #开启驼峰是命名
      table-underline: true

# elasticsearch配置
#elasticsearch:
#  host: 101.37.31.188
#  port: 9200
#  schema: http
#  connectionRequestTimeOut: 10000
#  socketTimeOut: 30000
#  maxConnectNum: 100
#  maxConnectPerRoute: 100
#  uniqueConnectTimeConfig: false
#  uniqueConnectNumConfig: true
